AWSTemplateFormatVersion: '2010-09-09'
Description: Internal AI (Next.js container) on AWS Lambda + Function URL +
  DynamoDB users table (with GSI email) + configurable env (Botpress & LDAP)

Parameters:
  Env:
    Type: String
    Default: prod
    AllowedValues:
      - dev
      - uat
      - prod
    Description: Environment tag

  FunctionName:
    Type: String
    Default: internal-ai-bot
    Description: Lambda function name

  EcrImageUri:
    Type: String
    Default: 345034663883.dkr.ecr.ap-southeast-1.amazonaws.com/vz/internal-ai:prod
    Description: Full ECR image URI

  DeployVersion:
    Type: String
    Default: manual-0
    Description: Change this to force redeploy (e.g., timestamp)

  Memory:
    Type: Number
    Default: 1024
  Timeout:
    Type: Number
    Default: 30

  NextPublicUrl:
    Type: String
    Default: https://wiki.vietjetthai.com
    Description: Public domain

  # =========================
  # Botpress configuration
  # =========================
  BotpressWebhookUrl:
    Type: String
    Default: https://webhook.botpress.cloud/6e333992-4b6f-452f-9089-990386321bf5
    Description: Botpress webhook URL

  BotpressToken:
    Type: String
    NoEcho: true
    Default: bp_bak_Srfy7S2v84czR8AuNyUSY3EuDsDRZvXq6fYH
    Description: Botpress API token

  BotpressClientId:
    Type: String
    Default: 629e90eb-4b6f-4767-977a-686a81eeb449
    Description: Botpress client ID

  BotpressApiUrl:
    Type: String
    Default: https://api.botpress.cloud
    Description: Botpress API base URL

  JwtSecret:
    Type: String
    NoEcho: true
    Default: ''
    Description: JWT secret (leave blank if not used)

  BotId:
    Type: String
    Default: 84b23382-8059-4173-a155-287893828551
    Description: Botpress Bot ID

  BotPressAPIUserKey:
    Type: String
    Default: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZlMzMzOTkyLTRiYzItNDUyZi05MDg5LTk5MDM4NjMyMWJmNSIsImlhdCI6MTc2MjIyOTA5MX0.mczVeAPje72yHpPUgp3WngolqcubiQkKOVcPN69DtL8
    Description: Default x-user-key for Botpres API

  # =========================
  # LDAP Auth configuration
  # =========================
  NextPublicLdapAuthUrl:
    Type: String
    Default: https://ldap-auth.vietjetthai.com
    Description: Public URL of ldap-auth Function URL

  NextPublicClientId:
    Type: String
    Default: vz-wiki-frontend
    Description: OAuth client_id used by frontend

  NextPublicRedirectUri:
    Type: String
    Default: https://banhmi.vietjetthai.com/api/auth/callback
    Description: OAuth redirect URI used by frontend

  # =========================
  # Users table (DynamoDB)
  # =========================
  UsersTableName:
    Type: String
    Default: vz-users-botpress
    Description: DynamoDB table name for storing user info & secret_key

  UserEmailGSI:
    Type: String
    Default: gsi_email
    Description: DynamoDB table index for query

  # =========================
  # S3 configuration
  # =========================
  AssetsBucketName:
    Type: String
    Default: vz-internal-ai-prod
    Description: S3 bucket for internal AI documents & uploads

  AssetsBucketPrefix:
    Type: String
    Default: botpress/
    Description: Default prefix/folder inside bucket

  # =========================
  # Files table (DynamoDB)
  # =========================
  FilesTableName:
    Type: String
    Default: vz-internal-ai-files
    Description: DynamoDB table for uploaded files metadata

Conditions:
  IsDev: !Equals [!Ref Env, dev]
  IsUat: !Equals [!Ref Env, uat]
  IsProd: !Equals [!Ref Env, prod]

Resources:
  # IAM Role for Lambda
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${FunctionName}-role-${Env}
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: LambdaInvokePermissions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: AllowLambdaInvokeSelf
                Effect: Allow
                Action:
                  - lambda:InvokeFunction
                  - lambda:InvokeFunctionUrl
                Resource: '*'
        - PolicyName: DynamoDbAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: UsersTableAccess
                Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource:
                  - !GetAtt UsersTable.Arn
                  - !Sub ${UsersTable.Arn}/index/gsi_email

              - Sid: FilesTableAccess
                Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource:
                  - !GetAtt FilesTable.Arn
                  - !Sub ${FilesTable.Arn}/index/gsi_bucket_key
      Tags:
        - Key: Project
          Value: internal-ai
        - Key: Env
          Value: !Ref Env

  # DynamoDB table for users (with GSI for email)
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref UsersTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: gsi_email
          KeySchema:
            - AttributeName: email
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      SSESpecification:
        SSEEnabled: true
      Tags:
        - Key: Project
          Value: internal-ai
        - Key: Env
          Value: !Ref Env

  # DynamoDB table for internal AI files
  FilesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref FilesTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: file_id
          AttributeType: S
        - AttributeName: bucket_key
          AttributeType: S
        - AttributeName: created_at
          AttributeType: S
      KeySchema:
        - AttributeName: file_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: gsi_bucket_key
          KeySchema:
            - AttributeName: bucket_key
              KeyType: HASH
            - AttributeName: created_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      SSESpecification:
        SSEEnabled: true
      Tags:
        - Key: Project
          Value: internal-ai
        - Key: Env
          Value: !Ref Env

  # Lambda Function
  AppFn:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !If
        - IsProd
        - !Ref FunctionName
        - !Sub ${FunctionName}-${Env}
      PackageType: Image
      Code:
        ImageUri: !Ref EcrImageUri
      Role: !GetAtt LambdaRole.Arn
      MemorySize: !Ref Memory
      Timeout: !Ref Timeout
      Architectures:
        - x86_64
      Description: !Sub DeployVersion=${DeployVersion}
      Environment:
        Variables:
          APP_ENV: !Ref Env
          NODE_ENV: !If
            - IsDev
            - development
            - production
          PORT: '8080'
          NEXT_TELEMETRY_DISABLED: '1'
          AWS_LWA_ENABLE_COMPRESSION: 'true'
          AWS_LWA_ASYNC_INIT: 'true'
          NEXT_PUBLIC_APP_URL: !Ref NextPublicUrl

          # ===== Botpress =====
          BOTPRESS_WEBHOOK_URL: !Ref BotpressWebhookUrl
          BOTPRESS_TOKEN: !Ref BotpressToken
          BOTPRESS_CLIENT_ID: !Ref BotpressClientId
          BOT_PRESS_API_URL: !Ref BotpressApiUrl
          JWT_SECRET: !Ref JwtSecret
          BOT_ID: !Ref BotId
          BOTPRESS_API_USER_KEY: !Ref BotPressAPIUserKey

          # ===== LDAP =====
          NEXT_PUBLIC_LDAP_AUTH_URL: !Ref NextPublicLdapAuthUrl
          NEXT_PUBLIC_CLIENT_ID: !Ref NextPublicClientId
          NEXT_PUBLIC_REDIRECT_URI: !Ref NextPublicRedirectUri

          # ===== DynamoDB Users table =====
          USERS_TABLE: !Ref UsersTableName
          USERS_EMAIL_INDEX: !Ref UserEmailGSI
          # ===== DynamoDB Files table =====
          FILES_TABLE: !Ref FilesTableName
      Tags:
        - Key: Project
          Value: internal-ai
        - Key: Env
          Value: !Ref Env

  # LogGroup (optional but good practice)
  AppFnLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${FunctionName}
      RetentionInDays: 14

  # Lambda Function URL (public)
  AppFnUrl:
    Type: AWS::Lambda::Url
    Properties:
      TargetFunctionArn: !Ref AppFn
      AuthType: NONE
      Cors:
        AllowOrigins:
          - '*'
        AllowMethods:
          - GET
          - POST
          - PUT
          - PATCH
          - DELETE
        AllowHeaders:
          - '*'
  # =========================
  # S3 Bucket
  # =========================
  AssetsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref AssetsBucketName
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - Id: CleanupOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 90

  # Permissions (new AWS 2026 model)
  AppFnUrlPermissionUrl:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref AppFn
      Action: lambda:InvokeFunctionUrl
      Principal: '*'
      FunctionUrlAuthType: NONE

  AppFnUrlPermissionInvoke:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref AppFn
      Action: lambda:InvokeFunction
      Principal: '*'

Outputs:
  FunctionArn:
    Description: Lambda ARN
    Value: !GetAtt AppFn.Arn

  FunctionUrl:
    Description: Public Function URL
    Value: !GetAtt AppFnUrl.FunctionUrl

  UsersTableOut:
    Description: DynamoDB users table name
    Value: !Ref UsersTableName

  AssetsBucketOut:
    Value: !Ref AssetsBucketName

  FilesTableOut:
    Description: DynamoDB files table name
    Value: !Ref FilesTableName