AWSTemplateFormatVersion: '2010-09-09'
Description: Internal AI UAT (Next.js on Lambda + Function URL)  FULL ENV, SHARED ASSETS

# =========================================================
# PARAMETERS
# =========================================================
Parameters:
  Env:
    Type: String
    Default: uat
    AllowedValues:
      - dev
      - uat
      - prod

  FunctionName:
    Type: String
    Default: internal-ai-bot-uat

  EcrImageUri:
    Type: String
    Default: 345034663883.dkr.ecr.ap-southeast-1.amazonaws.com/vz/internal-ai:uat

  DeployVersion:
    Type: String
    Default: manual-0
    Description: Change to force redeploy

  Memory:
    Type: Number
    Default: 1024

  Timeout:
    Type: Number
    Default: 30

  # =========================
  # Botpress
  # =========================
  BotpressWebhookUrl:
    Type: String
    Default: https://webhook.botpress.cloud/6e333992-4bc2-452f-9089-990386321bf5

  BotpressToken:
    Type: String
    NoEcho: true

  BotpressClientId:
    Type: String
    Default: 629e90eb-4b6f-4767-977a-686a81eeb449

  BotpressApiUrl:
    Type: String
    Default: https://chat.botpress.cloud

  BotId:
    Type: String
    Default: 84b23382-8059-4173-a155-287893828551

  BotPressAPIUserKey:
    Type: String
    NoEcho: true

  JwtSecret:
    Type: String
    NoEcho: true
    Default: ''

  # =========================
  # LDAP
  # =========================
  NextPublicLdapAuthUrl:
    Type: String
    Default: https://ldap-auth.vietjetthai.com

  NextPublicClientId:
    Type: String
    Default: vz-wiki-frontend

  NextPublicRedirectUri:
    Type: String
    Default: https://wiki.vietjetthai.com/api/auth/callback

  NextPublicAppUrl:
    Type: String
    Default: https://wiki.vietjetthai.com

  # =========================
  # DynamoDB
  # =========================
  UsersTableName:
    Type: String
    Default: vz-users-botpress-uat

  UsersTablePK:
    Type: String
    Default: user_id

  UserEmailGSI:
    Type: String
    Default: gsi_email

  # ? SHARED WITH PRODUCTION
  FilesTableName:
    Type: String
    Default: vz-internal-ai-files

  FilesTablePK:
    Type: String
    Default: file_id

  # =========================
  # S3 (SHARED)
  # =========================
  AssetsBucketName:
    Type: String
    Default: vz-internal-ai-prod

  AssetsBucketPrefix:
    Type: String
    Default: banhmi/

  # =========================
  # CURATOR ROLE (ASSUME)
  # =========================
  CuratorRoleArn:
    Type: String
    Description: IAM Role ARN allowed to curate shared assets
    Default: arn:aws:iam::345034663883:role/internal-ai-assets-curator
    NoEcho: true

# =========================================================
# RESOURCES
# =========================================================
Resources:

  # -------------------------
  # IAM ROLE
  # -------------------------
  LambdaRole:
    Type: AWS::IAM::Role
    DependsOn:
      - UsersTable
    Properties:
      RoleName: internal-ai-bot-role-uat
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole

      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

      Policies:
        # DynamoDB
        - PolicyName: DynamoDbAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource:
                  - !GetAtt UsersTable.Arn
                  - !Sub ${UsersTable.Arn}/index/${UserEmailGSI}
                  - !Sub arn:aws:dynamodb:*:*:table/${FilesTableName}
                  - !Sub arn:aws:dynamodb:*:*:table/${FilesTableName}/index/*

        # S3 ? UAT: PUT ONLY (NO DELETE)
        - PolicyName: S3UploadOnly
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                Resource:
                  - !Sub arn:aws:s3:::${AssetsBucketName}/${AssetsBucketPrefix}*

        # Assume Curator Role
        - PolicyName: AssumeCuratorRole
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: sts:AssumeRole
                Resource: !Ref CuratorRoleArn

  # -------------------------
  # LAMBDA
  # -------------------------
  AppFn:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref FunctionName
      PackageType: Image
      Code:
        ImageUri: !Ref EcrImageUri
      Role: !GetAtt LambdaRole.Arn
      MemorySize: !Ref Memory
      Timeout: !Ref Timeout
      Architectures:
        - x86_64
      Description: !Sub DeployVersion=${DeployVersion}

      Environment:
        Variables:
          # ===== App =====
          APP_ENV: uat
          NODE_ENV: production
          NEXT_PUBLIC_APP_ENV: uat
          NEXT_PUBLIC_APP_URL: !Ref NextPublicAppUrl

          # ===== S3 =====
          S3_BUCKET_NAME: !Ref AssetsBucketName
          S3_BUCKET_PREFIX: !Ref AssetsBucketPrefix
          CURATOR_ROLE_ARN: !Ref CuratorRoleArn

          # ===== DynamoDB =====
          USERS_TABLE: !Ref UsersTableName
          USERS_TABLE_PK: !Ref UsersTablePK
          USERS_EMAIL_INDEX: !Ref UserEmailGSI
          FILES_TABLE: !Ref FilesTableName
          FILES_TABLE_PK: !Ref FilesTablePK

          # ===== Botpress =====
          BOTPRESS_WEBHOOK_URL: !Ref BotpressWebhookUrl
          BOTPRESS_TOKEN: !Ref BotpressToken
          BOTPRESS_CLIENT_ID: !Ref BotpressClientId
          BOT_PRESS_API_URL: !Ref BotpressApiUrl
          BOT_ID: !Ref BotId
          BOTPRESS_API_USER_KEY: !Ref BotPressAPIUserKey
          JWT_SECRET: !Ref JwtSecret

          # ===== LDAP =====
          LDAP_AUTH_URL: !Ref NextPublicLdapAuthUrl
          CLIENT_ID: !Ref NextPublicClientId
          REDIRECT_URI: !Ref NextPublicRedirectUri

  # -------------------------
  # FUNCTION URL
  # -------------------------
  AppFnUrl:
    Type: AWS::Lambda::Url
    Properties:
      TargetFunctionArn: !Ref AppFn
      AuthType: NONE

  AppFnUrlPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref AppFn
      Action: lambda:InvokeFunctionUrl
      Principal: '*'
      FunctionUrlAuthType: NONE

  # -------------------------
  # USERS TABLE (UAT ONLY)
  # -------------------------
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref UsersTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: gsi_email
          KeySchema:
            - AttributeName: email
              KeyType: HASH
          Projection:
            ProjectionType: ALL

# =========================================================
# OUTPUTS
# =========================================================
Outputs:
  FunctionUrl:
    Value: !GetAtt AppFnUrl.FunctionUrl

  UsersTableOut:
    Value: !Ref UsersTableName

  SharedAssetsBucket:
    Value: !Ref AssetsBucketName

  SharedFilesTable:
    Value: !Ref FilesTableName

  CuratorRoleArnOut:
    Value: !Ref CuratorRoleArn